.github/pull_request_template.md, CONTRIBUTING.md, README.md
This PR adds documentation for folks who are interested in contributing to the project.
=> Create initial contributor information

_data/translations.yml
This adds a french translation to translations.yml
Fixes #63 
=> Add french strings to translations.yml

_data/commands/basic.yml, _data/commands/files.yml
In the _data/commands folder, added hindi translations to all functions.
Fixes #60 
* [ ✔] My code matches the existing code style of this project.
* [✔ ] My content is localized for all of the locales that this project currently supports.
* [ ✔] I have tested my code and it successfully builds for GitHub Pages and validates as AMP.
=> Update : Added Hindi translation to _data/commands folder.

_data/translations.yml
Fixes #62- Added Hindi translations for General strings
* [ x My content is localized for all of the locales that this project currently supports.
=> Added translations for general strings in Hindi

i18n/fr/guides/open-terminal-macos.md
Translated the whole thing to french, but I'm not sure if we should localize "cheat sheet" or if the translations for "go menu" and "utilities" are correct.
Fixes #72
=> Add french translation to the open Terminal article

i18n/hi/guides/open-terminal-macos.md
Latest guidelines issued by the organizers
We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are submitted in a repository classified with the ‘hacktoberfest’ topic. The pull requests will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.
I sincerely hope you will help me
https://hacktoberfest.digitalocean.com/hacktoberfest-update
I am attaching the link too for your convenience.
This PR closes #68.
=> Add Hindi translations for the open terminal guide [HACKTOBER 2020]

i18n/fr/guides/basic-web-server-macos-linux.md
=> French translation

i18n/pt/404.html, i18n/pt/guides/basic-web-server-macos-linux.md, i18n/pt/guides/curl-rest-api.md, i18n/pt/guides/index.md, i18n/pt/guides/navigate-terminal.md, i18n/pt/guides/open-terminal-macos.md, i18n/pt/index.html
Add template files for pt translations
=> Add template files for pt translations

_data/translations.yml
=> Added Bahasa (Indonesian) translations for general strings

i18n/pt/404.html
404 error page translated into Portuguese as requested.
Issue #99 - Create a Portuguese translation of the 404 error page
=> Page translated into Portuguese

i18n/id/404.html
404 error page translated into Bahasa Indonesia as requested.
Fixes #86 - Create an Indonesian translation of the 404 error page
=> Added Bahasa Indonesia translations for 404 page

_includes/body-button-copy.html, _includes/body-button-show-hide.html, _includes/i18n/index.html
Implemented copy button and show me buttons as includes
Fixes #12 
=> Implement copy button and show me buttons as includes

_includes/head-styles.html
Removed items that fail AMP validation
=> Removed items that fail AMP validation

_data/translations.yml
Added telugu as te.
Added telugu  as te. 
Fixes #89 89<-- Add the issue number so that it automatically closes the issue_
=> Update translations.yml Added Telugu as te.

_data/commands/files.yml
Added Portuguese translations for file command descriptions #115
Fixes #115 
=> 📝 add Portuguese translations for files.yml

_data/commands/files.yml, _data/guides/guide-index.yml
Fixes # _<-- Add the issue number so that it automatically closes the issue_
=> translation of added portuguese files (files.yml and guide-index.yml)

_data/commands/files.yml
Reconciles the two `pt` translations in `files.yml`.
=> Reconcile two pt translations

i18n/fr/guides/navigate-terminal.md
I added guide in french language !
Fixes #71
note : if there is any issue please tell me i will fix if not and you are going to merge it then please dont forgot to use hacktoberfest-accepted label as they updated rules
=> Add French translation for navigate-terminal.md

i18n/te/guides/basic-web-server-macos-linux.md
=> Add Telugu translation for basic-web-server-macos-linux.md

i18n/id/guides/basic-web-server-macos-linux.md
Added Indonesian translation of the basic web server guide
Fixes #116
=> Added Indonesian translation of the basic web server guide

i18n/id/guides/navigate-terminal.md
Indonesian translation of the navigate terminal guide
Fixes #118 - Create a Indonesian translation of the navigate terminal guide
=> Add Indonesian  translation of the navigate terminal guide

i18n/id/guides/open-terminal-macos.md
Added Indonesian translation of the open terminal guide
Fixes #122 
=> Add Indonesian translation of the open terminal guide

i18n/id/guides/curl-rest-api.md
Added Bahasa Indonesia (Indonesia) translation for the curl API rest guide
Fixes #117 
=> Added Indonesia translation for the curl rest API guide

_data/commands/basic.yml, _data/commands/files.yml, i18n/id/guides/basic-web-server-macos-linux.md, i18n/id/guides/curl-rest-api.md, i18n/id/guides/navigate-terminal.md, i18n/id/guides/open-terminal-macos.md
This PR cleans up the YAML file formatting to match the de facto standard found online. Additionally, it tries to standardize some of the language across the `id` translations without changing the material or consulting an expert.
=> Clean up the YAML files and standardize a bit

i18n/pt/guides/basic-web-server-macos-linux.md
Adds a Brazilian Portuguese translation for the basic-web-server-macos-linux guide
Fixes #109
=> Adds portuguese translation of the web server guide

i18n/te/404.html
Added telugu translation for the 404 page.
Fixes #84 
=> added 404 page translation in telugu

_data/translations.yml
Added russian translation for general strings in **translations.yml**
Fixes #146 
* [x ] My code matches the existing code style of this project.
* [ x] This is a new localization for existing content.
* [x ] I have tested my code and it successfully builds for GitHub Pages and validates as AMP.
=> added russian translation for general strings

i18n/pt/404.html
Since the 404 page was already translated, this PR merges in the changes from RenatoSiqueira in #102.
=> Update pt 404 page page on PR from contributor

_includes/head-meta.html
Fixes the Apple icon URL, as it was incorrectly relative.
=> Fix icon URL

_data/translations.yml
Added Bengali (Bangla) translations for general strings in **translations.yml**
Fixes #148 
* [ x] My code matches the existing code style of this project.
* [x ] This is a new localization for existing content.
* [ x] I have tested my code and it successfully builds for GitHub Pages and validates as AMP.
=> Added Bengali (Bangla) translations for general strings

_data/translations.yml
Fixes #147 
* [X ] My code matches the existing code style of this project.
=> Add Japanese translations for _data/translations.yml (#147)

_data/translations.yml
Add Chinese (Simplified) translations for general strings
Fixes #149  _<-- Add the issue number so that it automatically closes the issue_
=> Add: Simplified Chinese Translation (#149)

_data/commands/basic.yml, _data/commands/files.yml, _data/guides/guide-index.yml
Add translations for command descriptions in French
Fixes #61
=> Add translations for command descriptions in French

_data/commands/basic.yml, _data/commands/files.yml
Added Japanese translations into command descriptions for basic.yml and files.yml.
Added Chinese (Simplified) translations into command descriptions for basic.yml and files.yml.
Fixes #166 and #167 
=> Added Japanese and Chinese (Simplified) translations - fixed issue #166, #167

_data/commands/basic.yml, _data/commands/files.yml
Add translation for Bengali (Bangla) for Localization.
Fixes #174
=> Add Bengali (Bangla) translations

i18n/bn/404.html
Including 404 for Bengali.
I have a doubt why in bn still going to the /en/ version? Where should I change? I didn't found it.
Fixes #185 
=> Include 404 bn

_data/commands/basic.yml, _data/commands/files.yml
Added tamil translations for command descriptions
Fixes #175 
=> Add Tamil translations for command descriptions

i18n/zh-CN/404.html
Fixes #180 _<-- Add the issue number so that it automatically closes the issue_
=> Add new zh-CN translation for 404.html

_data/commands/basic.yml, _data/commands/files.yml
Added translations for Russian language
Fixes #186 
=> Include translations for Russian Language

_data/translations.yml, _includes/body-navbar.html, i18n/fr/guides/curl-rest-api.md, i18n/fr/guides/index.md, i18n/fr/guides/navigate-terminal.md, i18n/fr/guides/open-terminal-macos.md, i18n/fr/index.html
Enable `fr` locale and fix bugs to support it
=> Enable `fr` locale and fix bugs to support it

i18n/pt-BR/guides/basic-web-server-macos-linux.md
=> Fix link error

_includes/head-fonts.html, _includes/head-scripts.html
=> Fix fonts path

Gemfile.lock, _includes/head-styles.html
Quick CSS fix for side menu when in an AR locale.
=> Fix nav for lang AR
